require("__metal-and-stars-fariels-fork__.prototypes.categories.ammo-category")

require("__metal-and-stars-fariels-fork__.prototypes.dependency-updates.armoured-biter-updates")
require("__metal-and-stars-fariels-fork__.prototypes.dependency-updates.tenebris-updates")
require("__metal-and-stars-fariels-fork__.prototypes.dependency-updates.maraxsis-updates")
require("__metal-and-stars-fariels-fork__.prototypes.dependency-updates.planet-lib-tiers")

require("__metal-and-stars-fariels-fork__.prototypes.planet.routes")
require("__metal-and-stars-fariels-fork__.prototypes.planet.shipyard.shipyard_planet")
require("__metal-and-stars-fariels-fork__.prototypes.planet.shipyard.shipyard_tiles")
require("__metal-and-stars-fariels-fork__.prototypes.planet.nix.nix_planet")
require("__metal-and-stars-fariels-fork__.prototypes.planet.nix.nix_tiles")
require("__metal-and-stars-fariels-fork__.prototypes.planet.nix.decoratives-nix")
require("__metal-and-stars-fariels-fork__.prototypes.planet.ringworld.ringworld_planet")
require("__metal-and-stars-fariels-fork__.prototypes.planet.ringworld.ringworld_tiles")
require("__metal-and-stars-fariels-fork__.prototypes.planet.ringworld.decoratives-ringworld")
require("__metal-and-stars-fariels-fork__.prototypes.planet.ringworld.ringworld_resource_expressions")
require("__metal-and-stars-fariels-fork__.prototypes.planet.ostendus.mirandus_system")
require("__metal-and-stars-fariels-fork__.prototypes.planet.technology-basic")
require("__metal-and-stars-fariels-fork__.prototypes.planet.technology-advanced")
require("__metal-and-stars-fariels-fork__.prototypes.planet.technology-infinite")
require("__metal-and-stars-fariels-fork__.prototypes.planet.technology-addendums")
require("__metal-and-stars-fariels-fork__.prototypes.fluid")
require("__metal-and-stars-fariels-fork__.prototypes.item.item")
require("__metal-and-stars-fariels-fork__.prototypes.item.bacteria")
require("__metal-and-stars-fariels-fork__.prototypes.item.item-groups")
require("__metal-and-stars-fariels-fork__.prototypes.entity.space-chest")
require("__metal-and-stars-fariels-fork__.prototypes.entity.robot-enemies")
require("__metal-and-stars-fariels-fork__.prototypes.entity.prototype-mech-armor")
require("__metal-and-stars-fariels-fork__.prototypes.entity.prototype-mech-armor-animations")
require("__metal-and-stars-fariels-fork__.prototypes.entity.particle-accelerator")
require("__metal-and-stars-fariels-fork__.prototypes.entity.gravity-assembler")
require("__metal-and-stars-fariels-fork__.prototypes.entity.chemical-stager")
require("__metal-and-stars-fariels-fork__.prototypes.entity.microculture-vat")
require("__metal-and-stars-fariels-fork__.prototypes.entity.resources")
require("__metal-and-stars-fariels-fork__.prototypes.entity.quantum-stabilizer")
require("__metal-and-stars-fariels-fork__.prototypes.entity.conduit")
require("__metal-and-stars-fariels-fork__.prototypes.entity.zerog-lab")
require("__metal-and-stars-fariels-fork__.prototypes.entity.liquid-fuel-heating-tower")
require("__metal-and-stars-fariels-fork__.prototypes.entity.flying-robots")
require("__metal-and-stars-fariels-fork__.prototypes.recipe-category")
require("__metal-and-stars-fariels-fork__.prototypes.recipe")
require("__metal-and-stars-fariels-fork__.prototypes.recipes-conversions")
require("__metal-and-stars-fariels-fork__.prototypes.recipes-rocket-parts")
require("__metal-and-stars-fariels-fork__.prototypes.recipes-liquid-fuel")
require("__metal-and-stars-fariels-fork__.prototypes.recycling")
require("__metal-and-stars-fariels-fork__.prototypes.ammos")
--require("__metal-and-stars-fariels-fork__.prototypes.entity.accumulators") NYI
require("__metal-and-stars-fariels-fork__.prototypes.autoplace-controls")
require("__metal-and-stars-fariels-fork__.prototypes.units")
require("__metal-and-stars-fariels-fork__.prototypes.gravitons")
require("__metal-and-stars-fariels-fork__.prototypes.entity.asteroids.asteroid")
require("__metal-and-stars-fariels-fork__.prototypes.entity.asteroids.smoke")
require("__metal-and-stars-fariels-fork__.prototypes.entity.asteroids.explosions")
require("__metal-and-stars-fariels-fork__.prototypes.entity.asteroids.particles")
require("__metal-and-stars-fariels-fork__.prototypes.entity.asteroids.particle-animations")
require("__metal-and-stars-fariels-fork__.prototypes.entity.asteroids.factoriopedia-simulations")
require("__metal-and-stars-fariels-fork__.prototypes.planet.starsystem")
-- require("__metal-and-stars-fariels-fork__.prototypes.planet.volantus.volantus_planet")
-- require("__metal-and-stars-fariels-fork__.prototypes.planet.volantus.volantus_tiles")
-- require("__metal-and-stars-fariels-fork__.prototypes.planet.volantus.volantus_resource_expressions")
-- require("__metal-and-stars-fariels-fork__.prototypes.entity.volantus-assembler")
-- require("__metal-and-stars-fariels-fork__.prototypes.entity.volantus-platform")

require("__metal-and-stars-fariels-fork__.prototypes.dependency-updates.quality-updates")
require("__metal-and-stars-fariels-fork__.prototypes.dependency-updates.redrawn-space-connections-updates")

